sudo: required
dist: trusty
language: node_js
node_js:
- '9'

before_script:
  - npm install -g @angular/cli
  - npm install -g karma
  - npm install
  - npm run build
  - npm run lint
  - npm run e2e

script: karma start karma.conf.js --single-run